config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  get 'sessions/new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root   'users#new'
  get    '/chef_home', to: 'static_pages#chef_home'
  get    '/user_home', to: 'static_pages#user_home'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users do
    resource :chefs
  end
  resources :chefs, only: :index, shallow: true do
    resources :meals
  end
end

app/models/chef.rb
class Chef < ApplicationRecord

  belongs_to :user

  validates :user_id,
            presence: true,
            uniqueness: true

  validates :business_name, :business_description,
            presence: true


  has_many :meals
  has_and_belongs_to_many :cuisines
  has_and_belongs_to_many :dietary_accommodations
  has_and_belongs_to_many :certifications

  scope :for_clients, -> do
    left_outer_joins(:cuisines).includes(:cuisines)
         .left_outer_joins(:dietary_accommodations).includes(:dietary_accommodations)
         .left_outer_joins(:certifications).includes(:certifications)
         .left_outer_joins(:meals).includes(:meals)
  end

end

app/controllers/chefs_controller.rb
class ChefsController < ApplicationController

  before_action :require_login, except: %i[new create]

  def index
    keys = params[:report_form][:q].split() if params[:report_form]
    @chefs = []
    return unless keys

    meals_like_array = keys.map do |key|
      "meals.description LIKE '%#{key}%'"
    end
    meals_like_string = meals_like_array.join(' OR ')

    biz_desc_like_array = keys.map do |key|
      "business_description LIKE '%#{key}%'"
    end
    biz_desc_like_str = biz_desc_like_array.join(' OR ')

    biz_name_like_array = keys.map do |key|
      "business_name LIKE '%#{key}%'"
    end
    biz_name_like_str = biz_name_like_array.join(' OR ')

    @chefs = Chef.for_clients.where(cuisines: { name: keys })
                 .or(Chef.for_clients.where(dietary_accommodations: { name: keys }))
                 .or(Chef.for_clients.where(meals_like_string))
                 .or(Chef.for_clients.where(certifications: { name: keys }))
                .or(Chef.for_clients.where(biz_name_like_str))
                .or(Chef.for_clients.where(biz_desc_like_str)).distinct

    if params[:radius] != 'N/A'
      @chefs = @chefs.select do |chef|
        chef.user.distance_to(@current_user) <= params[:radius].to_f
      end
    end
  end

  def new
    @user = User.find_by(id: params[:user_id])
    @chef = Chef.new(user: @user)
  end

  def create
    user = User.find_by(id: params[:user_id])
    @chef = Chef.new(chef_params) do |chef|
      chef.user = user
    end
    if @chef.save
      flash.now[:alert] = 'Successfully created chef account.'
      log_in(user)
      redirect_to user_chefs_path(user)
    else
      flash.now[:alert] = 'Unable to create chef account.'
      render :new
    end
  end

  def show
    @chef = User.find_by(id: params[:user_id]).chef
    raise ActiveRecord::RecordNotFound unless @chef
  end

  def edit
    @chef = User.find_by(id: params[:user_id]).chef
    raise ActiveRecord::RecordNotFound unless @chef
  end

  def update
    @chef = User.find_by(id: params[:user_id]).chef
    raise ActiveRecord::RecordNotFound unless @chef
    if @chef.update(chef_params)
      redirect_to chef_meals_path(@chef), notice: 'Chef updated successfully'
    else
      #validation errors
      render 'edit'
    end
  end

  def delete
  end

  def chef_params
    params.require(:chef)
        .permit(:business_name, :business_description, cuisine_ids: [],
                dietary_accommodation_ids: [], certification_ids: [])
  end
end

app/helpers/chefs_helper.rb
module ChefsHelper
end

app/views/chefs/_chef_form.html.haml
.form-group
  = form.label :business_name, class: :required
  = form.text_field :business_name, class: [:focus, 'form-control']
.form-group
  = form.label :business_description, class: :required
  = form.text_field :business_description, class: 'form-control'
.form-row
  .form-group.col
    %strong Cuisines
    = form.collection_check_boxes(:cuisine_ids, Cuisine.all, :id, :name) do |cuisine|
      .cuisine
        = cuisine.check_box
        = cuisine.label
  .form-group.col
    %strong Dietary Accommodations
    = form.collection_check_boxes(:dietary_accommodation_ids, DietaryAccommodation.all, :id, :name) do |acc|
      .accommodation
        = acc.check_box
        = acc.label
  .form-group.col
    %strong Certifications
    = form.collection_check_boxes(:certification_ids, Certification.all, :id, :name) do |cert|
      .certification
        = cert.check_box
        = cert.label
.form-group
  = form.submit button_text, class: ['btn btn-primary', 'form-control']

app/views/chefs/edit.html.haml
.container.page-content
  %h2 Tell us more about your business.

  .errors
    = render 'shared/form_errors', resource: @chef

  .row.justify-content-center
    .col
      = form_for :chef, url: user_chefs_path(@chef.user), method: :put do |form|
        = render 'chefs/chef_form', form: form, button_text: 'Update Profile'

app/views/chefs/index.html.haml
.container.page-content
  %h2 Find Chefs
  .row
    .col-sm
      = form_for :report_form, method: :get do |f|
        .form-group
          = f.label 'Filter by keywords:'
        .form-group
          = f.text_field :q
          = f.submit 'Search', class: 'btn btn-primary'
        .form-group
          = f.label 'Filter by distance (miles):'
          = select_tag(:radius, options_for_select(['N/A', 1, 5, 10, 20, 50]))

      - if @chefs.length == 0
        %p
          %strong No chefs found.
      - else
        %p
          %strong Found #{@chefs.length} chefs in your area.
        - @chefs.each do | chef |
          .card
            .card-header
              = User.find_by_id(chef.user_id).full_name
            .card-body
              %h3.card-title
                = chef.business_name
              %p.card-text
                = chef.business_description
              %p
                = "Distance: #{chef.user.distance_to(@current_user).to_d.truncate(1)} miles"
            .card-body
              = link_to 'View Profile', user_chefs_path(User.find_by_id(chef.user_id)), class: 'btn btn-primary'

app/views/chefs/new.html.haml
.container.page-content
  %h2 Tell us more about your business.

  .errors
    = render 'shared/form_errors', resource: @chef

  .row.justify-content-center
    .col
      = form_for [@chef.user, @chef] do |form|
        = render 'chefs/chef_form', form: form, button_text: 'Sign Up As A Chef'

app/views/chefs/show.html.haml
.container.page-content
  .row
    .col-sm-3
      %h2
        = @chef.user.full_name
    .col
      - if @chef.user == current_user
        = link_to 'Edit Profile', edit_user_chefs_path(@chef.user), class: 'btn btn-primary'
  .row
    .col.business

      .business-name
        %strong= @chef.business_name

      .business-description
        = @chef.business_description

  %hr

  .row
    .dietary-accommodations.col-md
      %strong Dietary Accommodations
      - @chef.dietary_accommodations.each do |acc|
        .accommodation
          = acc.name
    .certifications.col-md
      %strong Certifications
      - @chef.certifications.each do |cert|
        .certifiction
          = link_to(cert.url, target: '_blank') do
            = cert.name
    .cuisines.col-md
      %strong Cuisines
      - @chef.cuisines.each do |cuisine|
        .cuisine
          = cuisine.name


  %hr

  .row
    .col-sm-3.meals
      %h3 Meals Offered

    .col
      - if @chef.user == current_user
        = link_to 'Edit Meals', chef_meals_path(@chef), class: 'btn btn-primary'

  .row
    - @chef.meals.each do |meal|
      - if meal.active?
        .card.meal-card
          = image_tag('tiffin_cover.jpg', class: 'card-img-top')
          .card-body
            %h4.card-title= meal.short_name
            .price
              = "$#{meal.price.to_d.truncate(2).to_f}"
            %p.card-text= meal.description
          %ul.list-group.list-group-flush
            .list-group-item
              %h5
                Cuisine
              - meal.cuisines.each do |cuisine|
                .meal-card__enumerable
                  = cuisine.name
            .list-group-item
              %h5
                Dietary Accomodations
              - meal.dietary_accommodations.each do |acc|
                .meal-card__enumerable
                  = acc.name