config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  get 'sessions/new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root   'users#new'
  get    '/chef_home', to: 'static_pages#chef_home'
  get    '/user_home', to: 'static_pages#user_home'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users do
    resource :chefs
  end
  resources :chefs, only: :index, shallow: true do
    resources :meals
  end
end

app/models/meal.rb
class Meal < ApplicationRecord
  validates :short_name, :description,
            presence: true

  validates :active,
            inclusion: {
                in: [true, false],
                message: "can't be blank"
            }

  validates :price,
            presence: true,
            numericality: {greater_than_or_equal_to: 0}

  belongs_to :chef
  has_and_belongs_to_many :cuisines
  has_and_belongs_to_many :dietary_accommodations

end

app/controllers/meals_controller.rb
class MealsController < ApplicationController

  before_action :find_chef, only: %i[index new create]

  def index
    @meals = @chef.meals
  end

  def new
    @meal = Meal.new(chef: @chef)
  end

  def create
    @meal = Meal.new(meal_params) { |meal| meal.chef = @chef }
    if @meal.save
      redirect_to chef_meals_path(@chef), notice: 'Meal created successfully'
    else
      #validation errors
      render 'new'
    end
  end

  def show
    @meal = Meal.find_by(id: params[:id])
    raise ActiveRecord::RecordNotFound unless @meal
  end

  def edit
    @meal = Meal.find_by(id: params[:id])
    raise ActiveRecord::RecordNotFound unless @meal
  end

  def update
    @meal = Meal.find_by(id: params[:id])
    @chef = @meal.chef
    raise ActiveRecord::RecordNotFound unless @meal
    if @meal.update(meal_params)
      redirect_to chef_meals_path(@chef), notice: 'Meal updated successfully'
    else
      #validation errors
      render 'new'
    end
  end

  def destroy
    @meal = Meal.find_by(id: params[:id])
    raise ActiveRecord::RecordNotFound unless @meal
    chef = @meal.chef
    if @meal.destroy
      redirect_to chef_meals_path(chef)
    else
      render 'index'
    end
  end

  def meal_params
    params.require(:meal)
        .permit(:short_name, :description, :price, :active,
                cuisine_ids: [],
                dietary_accommodation_ids: [])
  end

  private

  def find_chef
    @chef = Chef.find_by(id: params[:chef_id])
  end

end

app/views/meals/_meal_form.html.haml
.form-group
  = form.label :short_name, class: :required
  = form.text_field :short_name, class: 'focus form-control'
.form-group
  = form.label :description, class: :required
  = form.text_field :description, class: 'form-control'
.form-group
  = form.label :price, class: :required
  = form.text_field :price, class: 'form-control' #, type: 'number', min: 0.0, step: 0.01
.form-group
  %strong Should this meal be visible to customers?
  %br
  = form.label 'active_true', 'Yes'
  = form.radio_button :active, true
  = form.label 'active_false', 'No'
  = form.radio_button :active, false
.form-row
  .form-group.col
    %strong Cuisines
    .form-row
      = form.collection_check_boxes(:cuisine_ids, Cuisine.all, :id, :name) do |cuisine|
        .cuisine.col-6
          = cuisine.check_box
          = cuisine.label
  .form-group.col
    %strong Dietary Accommodations
    = form.collection_check_boxes(:dietary_accommodation_ids, DietaryAccommodation.all, :id, :name) do |acc|
      .accommodation
        = acc.check_box
        = acc.label
%div.form-group
  = form.submit button_text, class: 'btn btn-primary'

app/views/meals/edit.html.haml
.container.page-content
  %h2 Edit Meal

  .row.justify-content-center
    .col
      = form_for(:meal, url: meal_path, method: :put) do |form|
        = render 'meals/meal_form', form: form, button_text: 'Update Meal'

app/views/meals/index.html.haml
.container.page-content
  .row
    - @meals.each do | meal |
      .card.meal-card
        = image_tag('tiffin_cover.jpg', class: 'card-img-top')
        .card-body
          %h4.card-title
            = meal.short_name
          .price
            = "$#{meal.price.to_d.truncate(2).to_f}"
          %p.card-text
            = meal.description
        %ul.list-group.list-group-flush
          %li.list-group-item
            %h5
              Cuisine
            - meal.cuisines.each do |cuisine|
              .meal-card__enumerable
                = cuisine.name
          %li.list-group-item
            %h5
              Dietary Accomodations
            - meal.dietary_accommodations.each do |acc|
              .meal-card__enumerable
                = acc.name
        .card-body
          %p
            = link_to 'Edit', edit_meal_path(meal), class: 'btn btn-primary'
            = link_to 'Delete', meal_path(meal), {method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-primary'}
  = link_to 'Add New Meal', new_chef_meal_path(), class: 'btn btn-primary'

app/views/meals/new.html.haml
.container.page-content
  %h2 Create New Meal

  .row.justify-content-center
    .col
      = form_for(:meal, url: chef_meals_path) do |form|
        = render 'meals/meal_form', form: form, button_text: 'Create Meal'

app/views/meals/show.html.haml
Show Meal Page
%h3
  #{@meal.short_name} is delicious!