config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  get 'sessions/new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root   'users#new'
  get    '/chef_home', to: 'static_pages#chef_home'
  get    '/user_home', to: 'static_pages#user_home'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users do
    resource :chefs
  end
  resources :chefs, only: :index, shallow: true do
    resources :meals
  end
end

app/views/layouts/_footer.html.haml
%footer.footer.container-fluid

app/views/layouts/_header.html.haml
%header.header
  .header__left
    = link_to root_path, class: "header__home" do
      = image_tag('lunchbox.svg', class: 'header__image')
  .header__left
    = link_to root_path, class: "header__home" do
      %h1.header__title
        Tiffin.
  = render 'layouts/nav'

app/views/layouts/_messages.html.haml
- flash.each do |type, message|
  - if type == 'alert'
    .alert.bg-danger
      = message.html_safe
  - elsif type == 'notice'
    .alert.bg-success
      = message.html_safe

-#- if notice
-#  .alert.bg-success
-#    = notice.html_safe
-#
-#- if alert
-#  .alert.bg-danger
-#    = alert.html_safe

app/views/layouts/_nav.html.haml
.header__right
  %nav.header-nav
    - if current_user
      .header-nav__item
        = link_to 'Find Chefs', chefs_path
    .header-nav__item
      = create_signin_link

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title
      Tiffin
    = csrf_meta_tags

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  %body
    = render 'layouts/header'
    %div.header__offset
    = render 'layouts/messages'
    = yield
    = render 'layouts/footer'